import React from 'react';
import { Box, Typography } from '@mui/material';
import { motion } from 'framer-motion';
import { ArrowForward } from '@mui/icons-material';

import {
  PageShell,
  Section,
  Eyebrow,
  SectionHeading,
  Body,
  cardSx,
  ink, line, soft, lime,
} from '@/theme/theme';

import DotNetLogo from '@/assets/images/staffing/AI & EdTech Services/technologies/dotnet/dotnet1.jpg';
import Goal1 from '@/assets/images/staffing/AI & EdTech Services/technologies/dotnet/dotnet2.jpg';
import Goal2 from '@/assets/images/staffing/AI & EdTech Services/technologies/dotnet/dotnet3.jpg';
import Goal3 from '@/assets/images/staffing/AI & EdTech Services/technologies/dotnet/dotnet4.jpg';
import Goal4 from '@/assets/images/staffing/AI & EdTech Services/technologies/dotnet/dotnet5.jpg';

const goals = [
  { title: 'Object-Oriented Programming Environment', text: 'Provide a consistent object-oriented programming environment for local storage and execution of object code, for local execution of code distributed over the internet or for remote execution.', image: Goal1 },
  { title: 'Providing a Coded Runtime Where', text: 'Minimize the likelihood of conflicts in the process of software deployment and version control. Safe execution of code is guaranteed, including code generated by an unknown or incompletely trusted third-party vendor. Eliminate performance issues with scripting runtimes or interpreted code.', image: Goal2 },
  { title: 'Design Guidelines', text: 'Provides consistent design guidelines for different types of applications, such as Windows applications, and web applications.', image: Goal3 },
  { title: 'Industry-Standard Interoperability', text: 'Provides industry-standard interoperability that ensures that .NET Framework code is integrated with any other code.', image: Goal4 },
];

const benefits = [
  { n: '01', title: 'Full Interoperability with Existing Code', text: 'Full interoperability with existing code.' },
  { n: '02', title: 'Complete and Absolute Interlanguage Interaction', text: 'Complete and absolute interlanguage interaction.' },
  { n: '03', title: 'A Base Class Library that Hides the Complexities of Using an API', text: 'A base class library that hides the complexities of using an API, call directly and offers a consistent object model for all programming languages that support .NET.' },
  { n: '04', title: 'A Common Runtime Environment for Any .NET Applications', text: 'A common runtime environment for any .NET applications, regardless of the languages in which they are created. One of the important points is that all languages use the same set of built-in data types.' },
  { n: '05', title: 'Truly Simplifying the Application Deployment Process', text: 'In .NET, there is no need to register double types in the system registry. Moreover, .NET allows different versions of the same assembly to coexist peacefully on the same machine.' },
];

const DotNet = () => {
  return (
    <PageShell>
      <Box
        sx={{
          position: 'relative',
          marginTop: { xs: '72px', sm: '76px', md: '92px', lg: '100px' },
          minHeight: { xs: 480, md: 560 },
          padding: { xs: '7rem 1rem 3rem', md: '9rem 2.5rem 4rem' },
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          overflow: 'hidden',
          backgroundImage: `url(${DotNetLogo})`,
          backgroundSize: 'cover',
          backgroundPosition: 'center',
          backgroundRepeat: 'no-repeat',
          backgroundColor: ink,
          isolation: 'isolate',
        }}
      >
        <Box
          sx={{
            position: 'absolute',
            inset: 0,
            zIndex: -1,
            background: 'linear-gradient(180deg, rgba(255,255,255,.10) 0%, rgba(0,0,0,.65) 100%)',
          }}
        />

        <Box sx={{ maxWidth: 900, margin: '0 auto', textAlign: 'center', width: '100%', position: 'relative', zIndex: 2 }}>
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.6 }}>
            <Eyebrow sx={{ color: '#ffffff', textShadow: '0 2px 8px rgba(0,0,0,.95)' }}>Corporate Training</Eyebrow>
            <Typography
              component="h1"
              sx={{
                margin: '.5rem auto 1rem',
                font: "400 clamp(1.1rem, 2.2vw, 1.7rem)/1.15 Georgia, 'Times New Roman', serif",
                color: '#fff',
                maxWidth: 620,
                letterSpacing: 0,
                textShadow: '0 2px 12px rgba(0,0,0,.95), 0 1px 3px rgba(0,0,0,1)',
              }}
            >
              .NET Development Services <Box component="span" sx={{ color: lime }}>by ONAS Solutions</Box>
            </Typography>

            <Body sx={{ color: '#ffffff !important', maxWidth: 560, margin: '0 auto', textShadow: '0 1px 8px rgba(0,0,0,.95)' }}>
              The .NET Framework is a technology that supports the creation and execution of Windows web services and applications.
            </Body>
          </motion.div>
        </Box>
      </Box>

      <Section>
        <Box sx={{ textAlign: 'center', marginBottom: '2rem' }}>
          <Eyebrow>Design Goals</Eyebrow>
          <SectionHeading sx={{ marginTop: '.7rem', maxWidth: 800 }}>
            The .NET Framework Was Designed with the Following Goals
          </SectionHeading>
        </Box>

        <Box sx={{ display: 'grid', gridTemplateColumns: { xs: '1fr', sm: 'repeat(2, 1fr)', md: 'repeat(4, 1fr)' }, gap: { xs: '1rem', md: '1.2rem' } }}>
          {goals.map((b, i) => (
            <motion.div key={i} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.5, delay: (i % 4) * 0.05 }} style={{ display: 'flex', width: '100%' }}>
              <Box sx={{ ...cardSx, padding: 0, overflow: 'hidden', height: '100%', display: 'flex', flexDirection: 'column' }}>
                <Box sx={{ width: '100%', height: 100, overflow: 'hidden', borderBottom: `1px solid ${line}` }}>
                  <Box component="img" src={b.image} alt={b.title} sx={{ width: '100%', height: '100%', objectFit: 'cover', display: 'block' }} />
                </Box>
                <Box sx={{ padding: '1rem .9rem', display: 'flex', flexDirection: 'column', flexGrow: 1 }}>
                  <Typography component="h3" sx={{ margin: '0 0 .5rem', font: "400 clamp(.72rem, 1vw, .82rem)/1.25 Georgia, 'Times New Roman', serif", color: ink, textTransform: 'uppercase', letterSpacing: '.02em' }}>
                    {b.title}
                  </Typography>
                  <Body sx={{ fontSize: '.58rem', lineHeight: 1.65, flexGrow: 1 }}>{b.text}</Body>
                </Box>
              </Box>
            </motion.div>
          ))}
        </Box>
      </Section>

      <Section bg={soft}>
        <Box sx={{ textAlign: 'center', marginBottom: '2.5rem' }}>
          <Eyebrow>Benefits</Eyebrow>
          <SectionHeading sx={{ marginTop: '.7rem', maxWidth: 800 }}>
            .NET Benefits in Software Development
          </SectionHeading>
        </Box>

        <Box sx={{ maxWidth: 900, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
          {benefits.map((b, i) => (
            <motion.div key={i} initial={{ opacity: 0, y: 20 }} whileInView={{ opacity: 1, y: 0 }} viewport={{ once: true }} transition={{ duration: 0.5, delay: (i % 5) * 0.05 }}>
              <Box sx={{ display: 'flex', alignItems: 'flex-start', gap: '1.2rem' }}>
                <Typography sx={{ flexShrink: 0, font: "400 clamp(1.6rem, 3vw, 2.4rem)/1 Georgia, 'Times New Roman', serif", color: '#bcd0c5', letterSpacing: 0, minWidth: 48, lineHeight: 1 }}>
                  {b.n}
                </Typography>
                <Box>
                  <Typography component="h3" sx={{ margin: '0 0 .5rem', font: "400 clamp(.9rem, 1.4vw, 1.05rem)/1.25 Georgia, 'Times New Roman', serif", color: ink, textTransform: 'uppercase', letterSpacing: '.02em' }}>
                    {b.title}
                  </Typography>
                  <Body sx={{ fontSize: '.7rem', lineHeight: 1.8 }}>{b.text}</Body>
                </Box>
              </Box>
            </motion.div>
          ))}
        </Box>
      </Section>

      <Section>
        <Box sx={{ textAlign: 'center', maxWidth: 800, margin: '0 auto' }}>
          <Eyebrow>Get Started</Eyebrow>
          <SectionHeading sx={{ marginTop: '.7rem', marginBottom: '1rem' }}>
            Train Your Team on .NET
          </SectionHeading>
          <Body sx={{ marginBottom: '1.6rem' }}>
            Let&apos;s design a .NET training program that fits your engineers&apos; existing experience, your tech stack, and your delivery goals.
          </Body>
          <Box component="a" href="/resources/contact-us" sx={{ display: 'inline-flex', alignItems: 'center', gap: '.5rem', padding: '.7rem 1.1rem', borderRadius: '2px', background: '#0B4C74', color: '#ffffff', fontWeight: 600, fontSize: '.62rem', fontFamily: "'Poppins', sans-serif", textDecoration: 'none', transition: 'background .2s ease', '&:hover': { background: '#d3ffb0', color: '#000000' } }}>
            Request a Proposal <ArrowForward sx={{ fontSize: 14 }} />
          </Box>
        </Box>
      </Section>
    </PageShell>
  );
};

export default DotNet;